source-file ~/.tmux/.tmuxline.conf

if-shell "test -f [~/.tmux/.tmuxline.conf]" "source [~/.tmux/.tmuxline.conf]"

# r で .tmux.conf のリロード
bind r source-file ~/.tmux.conf \; display "Reloaded!"


# キーストロークのディレイを減らす
set -sg escape-time 1

# 256 色端末を使用する
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

# ウィンドウとペインの番号を 1 から開始
set -g base-index 1
setw -g pane-base-index 1
# ウィンドウを閉じた時に番号を詰める
set-option -g renumber-windows on

set-option -g mouse on

# Prefix + vim のキーバインドでペインを移動する
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Prefix + | でペインを垂直分割する
bind | split-window -h -c "#{pane_current_path}"
# Prefix + - でペインを水平分割する
bind - split-window -v -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Remap tpm uninstall from 'alt-u' to 'u'
set -g @tpm-clean 'u'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
