# Terminal
set -g default-terminal "tmux-256color"

# Prefix Key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable ESC Key
set -sg escape-time 0

# Mouse
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

# Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Toggle bottom pane
bind t if-shell '[[ $(tmux list-panes | wc -l) -eq 1 ]]' \
  'split-window -v -p 30 -c "#{pane_current_path}"' \
  'kill-pane -t bottom'

# Toggle right pane
bind r if-shell '[[ $(tmux list-panes | wc -l) -eq 1 ]]' \
  'split-window -h -p 30 -c "#{pane_current_path}"' \
  'kill-pane -t right'

# Plugins
set -g @plugin 'janoamaral/tokyo-night-tmux'

# TPM
run '~/.config/tmux/plugins/tpm/tpm'
