# espanso matches (snippets)
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Paths
  # - trigger: ";pj"
  #   replace: "~/Projects/"
  # - trigger: ";dot"
  #   replace: "~/ghq/github.com/yasainet/dotfiles/"
  - trigger: ";doc"
    replace: "~/Documents/"
  # Terms
  - trigger: ";js"
    replace: "JavaScript"
  - trigger: ";ts"
    replace: "TypeScript"
  - trigger: ";ne"
    replace: "Next.js"
  - trigger: ";node"
    replace: "Node.js"
  - trigger: ";su"
    replace: "Supabase"
  - trigger: ";ed"
    replace: "Edge Functions"
  - trigger: ";pg"
    replace: "PostgreSQL"
  # Services
  - trigger: ";cf"
    replace: "Cloudflare"
  - trigger: ";cc"
    replace: "Claude Code"
  - trigger: ";oc"
    replace: "OpenCode"
  - trigger: ";ve"
    replace: "Vercel"
  - trigger: ";se"
    replace: "Sentry"
  - trigger: ";co"
    replace: "ComfyUI"
  # Environments
  - trigger: ";dev"
    replace: "development"
  - trigger: ";prev"
    replace: "preview"
  - trigger: ";prod"
    replace: "production"
  # Date
  - trigger: ";date"
    replace: "{{d}}"
    vars:
      - name: d
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ";time"
    replace: "{{d}}"
    vars:
      - name: d
        type: date
        params:
          format: "%H:%M:%S"
  - trigger: ";now"
    replace: "{{d}}"
    vars:
      - name: d
        type: date
        params:
          format: "%Y/%m/%d %H:%M"
