matches:
  - trigger: ";pj"
    replace: "~/Projects/"
  - trigger: ";ne"
    replace: "Next.js"
  - trigger: ";no"
    replace: "Node.js"
  - trigger: ";su"
    replace: "Supabase"
  - trigger: ";ef"
    replace: "Supabase Edge Functions"
  - trigger: ";ts"
    replace: "TypeScript"
  - trigger: ";js"
    replace: "JavaScript"
  - trigger: ";pg"
    replace: "PostgreSQL"
  - trigger: ";ssr"
    replace: "Server-Side Rendering"
  - trigger: ";ssg"
    replace: "Static Site Generation"
  - trigger: ";isr"
    replace: "Incremental Static Regeneration"
  - trigger: ";sa"
    replace: "Server Actions"
  - trigger: ";sc"
    replace: "Server Components"
  - trigger: ";dot"
    replace: "~/dotfiles"
  - trigger: ";lint"
    replace: "~/Projects/eslint"
