[settings]

[db]
supabase = { host = "127.0.0.1", driver = "postgres", port = 54322, database = "postgres", username = "postgres", default = true }
ehdb = { host = "127.0.0.1", driver = "postgres", port = 5432, database = "ehentai_db", username = "ehdb" }
