return {
  require("plugins.treesitter"),
  require("plugins.tokyonight"),
  require("plugins.neo-tree"),
  require("plugins.lualine"),
  require("plugins.toggleterm"),
  require("plugins.gitsigns"),
  require("plugins.mason"),
  require("plugins.lsp"),
  require("plugins.cmp"),
  require("plugins.claudecode"),
  require("plugins.autopairs"),
  require("plugins.comment"),
  require("plugins.todo-comments"),
  require("plugins.indent-blankline"),
  require("plugins.codecompanion"),
}
