# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# prefix
set -g prefix C-b
unbind C-b
bind C-b send-prefix

# 同一ディレクトリで開く
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# 画面分割
bind - split-window -v
bind / split-window -h

# nord
set -g @plugin "arcticicestudio/nord-tmux"

# システムのクリップボードにコピー
set -g @plugin 'tmux-plugins/tmux-yank'

# tpmの初期化
run '~/.tmux/plugins/tpm/tpm'
